### ISSUE TITLE
Use client side time for fetch contributions data

### ISSUE THREAD

**Issue by LitoMore** [sallar/github-contributions-api#9]
We should use the client side date time to fetch the contributions data.

Here is my case, I'm in China, here is my contributions chart:

### Chart from GitHub

![image](https://user-images.githubusercontent.com/8186898/39678236-56ec0142-51bb-11e8-98b3-0e4ed3b2aeee.png)

### Chart from github-contributions.now.sh

<img width="40%" src="https://user-images.githubusercontent.com/8186898/39678253-88ca943a-51bb-11e8-9dc9-73ad9c759105.png" />

### My `Date()` in browser's console

```
> Date()
"Mon May 07 2018 05:59:06 GMT+0800 (China Standard Time)"
```

Is there any way get the client timezone from current `request`? If not, I think we should add user's timezone to the client's request (query or header).

I'll gladly make a pull request to fix this issue :)

**Comment by sallar** [comment]
The problem is that the server that reads your Github profile is located in Belgium. And right now there is no easy way to configure the server time since we're using Zeit's now service and no Docker containers. I understand that this might be frustrating but fixing this requires more work than this project was meant for. I'm sorry.

**Comment by LitoMore** [comment]
That's OK, closing ;)
